[workspace]
members = [
        "fastpay_core",
        "fastpay",
        "coconut",
        "bulletproofs",
        "benchmark_client"
]

[profile.release]
debug = true

[profile.bench]
debug = true
