[package]
name = "coconut"
version = "0.1.0"
edition = "2018"

[dependencies]
bls12_381 = { version="0.6.0", features=["experimental"] }
rand = "0.8.4"
ff = "0.11.0"
sha2 = "0.9.8"
group = "0.11.0"
thiserror = "1.0.29"